apiVersion: v1
stringData:
  MONGO_INITDB_ROOT_PASSWORD: toor
  MONGO_INITDB_ROOT_USERNAME: root
kind: Secret
metadata:
  name: db-secret-file
type: Opaque
---
apiVersion: v1
stringData:
  INSURANCE_EMAIL: "insuranceappdsbd@gmail.com" #To change
  EMAIL_PW: "yjUNr9ZKzQvfhAe"
kind: Secret
metadata:
  name: receipt-secret-file
type: Opaque